// Licensed to ObjectStyle LLC under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ObjectStyle LLC licenses
// this file to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.


== Programming Jetty Applications

You can write servlet specification objects (servlets, filters, listeners) as you'd do it under JavaEE, except that there's no `.war` and no `web.xml`. There's only your application, and you need to let Bootique know about your objects and how they should be mapped to request URLs. Let's start with servlets.

=== Servlets

The easiest way to add a servlet to a Bootique app is to annotate it with `@WebServlet`, providing name and url patterns:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/AnnotatedServlet.java[tags=AnnotatedServlet]
----

The "name" annotation is kind of important as it would allow to override annotation values in the YAML,
as described in the "Configuration Reference" chapter. A servlet created this way can inject any services it might need using normal Bootique DI injection.

Next step is adding it to Bootique via `JettyModule` contribution API called from your application Module:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/ModuleWithAnnotatedServlet.java[tags=bindAnnotatedServlet]
----

But what if you are deploying a third-party servlet that is not annotated? Or annotation values are off in the context
of your application? There are two choices. The first is to subclass such servlets and annotate the subclasses that
you control. The second is to wrap your servlet in a special metadata object called `MappedServlet`, providing all the
mapping information in that wrapper. This is a bit too verbose, but can be a good way to define the mapping that is not
otherwise available:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/ModuleWithMappedServlet.java[tags=bindMappedServlet]
----

Finally if we need to use MappedServlet for mapping servlet URLs and parameters, but also need the ability to initialize
the underlying servlet with environment dependencies, we can do something like this:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/ModuleWithMappedServletAndDI.java[tags=bindMappedServlet]
----

=== Servlet Filters

Just like servlets, you can annotate and register your filters:
[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/AnnotatedFilter.java[tags=AnnotatedFilter]
----

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/ModuleWithAnnotatedFilter.java[tags=bindAnnotatedFilter]
----

And just like with servlets you can use `MappedFilter` and `JettyModule.extend(..).addMappedFilter` to wrap a filter in app-specific metadata.

=== Listeners

Listeners are simpler then servlets or filters. All you need is to create classes that implement one of servlet
specification listener interfaces (`ServletContextListener`, `HttpSessionListener`, etc.) and bind them in your app:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/ModuleWithListener.java[tags=bindListener]
----

Listeners can rely on injection to obtain dependencies, just like servlets and filters.

[#serving-static-files]
=== Serving Static Files

Jetty is not limited to just servlets. It can also act as a webserver for static files stored on the filesystem or even
on the application classpath. To "publish" files in a given folder on Jetty, use the following API:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/StaticServlet.java[tags=staticServlet]
----

You can publish as many locations as needed. If a location is not known at compile time, it can alternatively
be defined in the app configuration with `resourceBase` servlet parameter:

[source,yaml]
----
jetty:
  servlets:
    docroot:
      params:
        # This follows Bootique resource URL format
        # and can be a "classpath:" URL or a filesystem path
        resourceBase: "classpath:com/example/docroot"
----

Another potentially relevant (and rather confusing) setting is `pathInfoOnly`. It controls URL-to-file resolving
behavior and is available as a part of the location publishing API, or as a servlet parameter. E.g.:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/StaticServletPathInfo.java[tags=pathInfo]
----

It behaves as follows:
|===
|URL|pathInfoOnly|File Path

|/abc/dir1/f1.html
|false (default)
|<resource_base>/abc/dir1/f1.html

|/abc/dir1/f1.html
|true
|<resource_base>/dir1/f1.html
|===

Jetty `DefaultServlet` (the one serving the static files under the hood) supports a number of other
parameters https://eclipse.dev/jetty/javadoc/jetty-11/org/eclipse/jetty/servlet/DefaultServlet.html[described here].
Some of them, such as `relativeResourceBase`, require the app-wide resource base to be set:

[source,yaml]
----
jetty:
  staticResourceBase: "classpath:com/example/docroot"
----

NOTE: `staticResourceBase` is really redundant in most (all?) situations, so hopefully you will never need to use it.

=== ServletEnvironment

Some application classes have direct access to the current servlet request and context (e.g. servlets, filters,
listeners are all passed the servlet environment objects in their methods). But other classes don't.
E.g. imagine you are writing an audit service that needs to know the request URL and the calling client IP address.
For such services Bootique provides an injectable `ServletEnvironment` object:

[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/ServiceWithServletEnvironment.java[tags=envInject]
----

Now any method in this class can access `ServletContext` or `HttpServletRequest`:
[source,java,indent=0]
----
include::../../../test/java/io/bootique/jetty/docs/ServiceWithServletEnvironment.java[tags=envRead]
----

Note that `ServletEnvironment` returns `Optional` for both, as there is no guarantee that it is invoked within a request
or after the Jetty engine initialized its servlets. It is the responsibility of the caller to verify the state of the
`Optional` and react accordingly, just like we did in this example.